### ISSUE TITLE
[Advice] Change titleid of sysmodule

### ISSUE THREAD

**Issue by masagrator** [crc-32/layoff#11] opened 2020-04-17 06:54 UTC
I don't know if you are aware of 10.0.0 new titleid validation check, but from this FW exefs sysmodules cannot be in range 0x0100000000010000 - 0x01FFFFFFFFFFFFFF
Otherwise they will be forced to exit.
My advice: just change "01" to anything else - 00, 42 or anything you want.

**Comment by exelix11** [comment] 2020-04-17 07:38
I remember this being mentioned on reswitched but has it been documented somewhere like switchbrew ? Cause crc32 is testing layoff on 10 and didn't seem to have issues.

**Comment by exelix11** [comment] 2020-04-17 07:43
Oh wait that's likely just for custom sysmodules, our title id is overlayDisp's or else we can't replace it.

**Comment by masagrator** [comment] 2020-04-17 08:02
I am not aware of any documentation on this.
Maybe your titleid is treated as valid? I don't know.
It's just without changing titleid nor ovlloader nor SaltyNX were working as exefs.
KIP didn't have any issues with it.

**Comment by exelix11** [comment] 2020-04-17 08:25
welp, guess it's worth to change the id before release just to be safe, added this in the todo list

**Comment by crc-32** [comment] 2020-04-17 10:16
Layoff is not a sysmodule, it's not loaded by boot2 as a sysmodule, it's a reimplementation of the overlayDisp applet which is it's own designated thing in horizon and the titleid is required to be what it is for horizon to load it as such.

**Comment by crc-32** [comment] 2020-04-17 10:19
Unless you're talking about the actual sysmodule for notifications, in which case `0x01006C61796F6666` fits in that range?

**Comment by crc-32** [comment] 2020-04-17 10:21
Ah, the issue is that it does fit in the range, in that case...

**Comment by exelix11** [comment] 2020-04-22 16:18
with the new titleid in Ipc-dev 13918968f0c0f9193f0ee4f8d20b679607b2c6e8 this should be fixed, i think we can close

**Closed as completed** 2020-04-25 12:53 UTC
Labels: bug, confirmed
